config/urls.py
# config/urls.py


from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from . import views
from django.urls import path

app_name = "website"

urlpatterns = [
    path('', views.home_page_view, name = 'home'),
    path('doors', views.doors_page_view, name = 'doors'),
    path('dire', views.dire_page_view, name = 'dire'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render

# Create your views here.

def home_page_view(request):
    context= {'sir' : "(Most Iconic)"}

    return render(request,"website/home.html", context)

def doors_page_view(request):
    context= {'sir' : "(Most Iconic)"}

    return render(request,"website/doors.html", context)

def dire_page_view(request):
    context= {'sir' : "(Most Iconic)"}

    return render(request,"website/dire.html", context)

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Rock Bands</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
</head>
<body>
<header class="jumbotron text-center">
    <h1>Rock Bands</h1>
    <p>{{sir}}</p>
<nav>
    <a href="{% url 'website:home' %}" class="btn btn-info">Home</a>
    <a href="{% url 'website:doors' %}" class="btn btn-info">The Doors</a>
    <a href="{% url 'website:dire' %}" class="btn btn-info">Dire Straits</a>
</nav>
</header>
<article class="container">
    <main class="col-sm-6">
	{% block main %}
	{% endblock main %}
    </main>
    <aside class="col-sm-6">
        <img src="{% load static %} {% static 'website/images/carl.png' %}" alt="">
    </aside>
</article>
<footer>Music</footer>
</body>
</html>

website/templates/website/dire.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>Dire Straits</h3>
    <p>Dire Straits were a British rock band formed in London in 1977 by Mark Knopfler (lead vocals and lead guitar), David Knopfler (rhythm guitar and backing vocals), John Illsley (bass guitar and backing vocals), and Pick Withers (drums and percussion). They were active from 1977 to 1988 and again from 1991 to 1995. Dire Straits are one of the world's best-selling music artists, with album sales of over 100 million.
        Their first single, "Sultans of Swing", from their 1978 self-titled debut album, reached the top ten in the UK and US charts. It was followed by hit singles including "Romeo and Juliet" (1981), "Private Investigations" (1982), "Twisting by the Pool" (1983), "Money for Nothing" (1985), and "Walk of Life" (1985).
        Their most commercially successful album, Brothers in Arms (1985), has sold more than 30 million copies; it was the first album to sell a million copies on compact disc,
        and is the eighth-bestselling album in UK history. According to the Guinness Book of British Hit Albums,
        Dire Straits have spent over 1,100 weeks on the UK albums chart, the fifth most of all time.
        Dire Straits' sound draws from various influences including country, folk, the blues rock of J. J. Cale, and jazz.
        Their stripped-down sound contrasted with punk rock and demonstrated a roots rock influence that emerged from pub rock.
        There were several changes in personnel, with Mark Knopfler and Illsley being the only members who lasted from the beginning of the band's existence, to the end.
        After their first breakup in 1988, Knopfler told Rolling Stone: "A lot of press reports were saying we were the biggest band in the world.
        There's not an accent then on the music, there's an accent on popularity. I needed a rest." They disbanded for good in 1995,
        after which Knopfler launched a solo career full-time. He has since declined reunion offers.
        Called "the biggest British rock band of the 80s" by Classic Rock magazine, their 1985–1986 world tour, which included a performance at Live Aid in July 1985,
        set a record in Australasia. Their final world tour from 1991 to 1992 sold 7.1 million tickets.
        Dire Straits won four Grammy Awards, three Brit Awards (Best British Group twice), two MTV Video Music Awards, and various other awards.
        They were inducted into the Rock and Roll Hall of Fame in 2018.</p>
{% endblock %}

website/templates/website/doors.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>The Doors</h3>
        <p>The Doors were an American rock band formed in Los Angeles in 1965, with vocalist Jim Morrison, keyboardist Ray Manzarek, guitarist Robby Krieger,
        and drummer John Densmore. They were among the most controversial and influential rock acts of the 1960s, mostly due to Morrison's lyrics, voice,
        and his erratic stage persona. They have been cited as one of the pioneers of psychedelia,
        and the group was widely regarded as an important part of the era's counterculture.
        The band took its name from the title of Aldous Huxley's book The Doors of Perception, itself a reference to a quote by William Blake.
        After signing with Elektra Records, the Doors with Morrison released six albums in five years, some of which are considered among the greatest of all time,
        including The Doors (1967), Strange Days (1967), and L.A. Woman (1971).
        They were one of the most successful bands during that time and by 1972 the Doors had sold over 4 million albums domestically and nearly 8 million singles.
        Morrison died in uncertain circumstances in 1971. The band continued as a trio until disbanding in 1973.
        They released three more albums in the 1970s, two of which featured earlier recordings by Morrison,
        and over the decades reunited on stage in various configurations. In 2002, Manzarek,
        Krieger and Ian Astbury of the Cult on vocals started performing as "The Doors of the 21st Century".
        Densmore and the Morrison estate successfully sued them over the use of the band's name. After a short time as Riders on the Storm,
        they settled on the name Manzarek–Krieger and toured until Manzarek's death in 2013.
        The Doors were the first American band to accumulate eight consecutive gold LPs. According to the RIAA,
        they have sold 33 million albums in the US and over 100 million records worldwide, making them one of the best-selling bands of all time.
        The Doors have been listed as one of the greatest artists of all time by magazines including Rolling Stone,
        which ranked them 41st on its list of the "100 Greatest Artists of All Time". In 1993, they were inducted into the Rock and Roll Hall of Fame.</p>
{% endblock %}

website/templates/website/home.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>General Info</h3>
    <p>Rock music is a broad genre of popular music that originated as "rock and roll" in the United States in the late 1940s and early 1950s,
        developing into a range of different styles in the mid-1960s and later, particularly in the United States and the United Kingdom.
        It has its roots in 1940s and 1950s rock and roll, a style that drew directly from the blues and rhythm and blues genres of African-American music and from country music.
        Rock music also drew strongly from a number of other genres such as electric blues and folk, and incorporated influences from jazz, classical,
        and other musical styles. For instrumentation, rock has centered on the electric guitar, usually as part of a rock group with electric bass, drums,
        and one or more singers. Usually, rock is song-based music with a 4|4 time signature using a verse–chorus form,
        but the genre has become extremely diverse. Like pop music,
        lyrics often stress romantic love but also address a wide variety of other themes that are frequently social or political.</p>
{% endblock %}